### ISSUE TITLE
Inference problem

### ISSUE THREAD

**Issue by kunc01** [maziao/T2I-Eval#1]
Thanks for your excellent work!
I've tried to inference with vllm+OpenAI Compatible Server, but due to network issues, I'm consistently getting "403 Forbidden" errors, so I turned to vllm+offline batched inference as shown in the images, but generated text seems to be nonsense, and failed to pass the later formatting in inference_engine.py.
<img width="676" alt="image" src="https://github.com/user-attachments/assets/59cc02f5-c33a-4380-97c9-1dd17e9d347b">
<img width="1460" alt="image" src="https://github.com/user-attachments/assets/3fd089c7-ce4e-4a65-b735-fec215e94535">
Any help is appreciated!

**Comment by maziao** [comment]
Thank you for your interest in our work!

Based on the situation you described, we suspect the issue may lie in the step of **deploying** the model using vllm. Please check whether the deployment was successful. You can refer to the output shown in the example below. If your command line displays similar output, it indicates that the model deployment was successful. Make sure the deployment is complete before running the inference script.

We hope this answer is helpful for you. If you have any further questions, please feel free to ask.

<img width="739" alt="image" src="https://github.com/user-attachments/assets/95f03926-bbc6-48c0-9afc-a74012362553">

**Comment by kunc01** [comment]
I've tried vllm deploy with different ports, and the "403 Forbidden" error persists. Actually I'm trying to find a simple way to modify the code for vllm+offline batched inference, but not succeeded yet.
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/5f7ab866-6c41-4b06-b1e9-76e393a81727">

**Comment by maziao** [comment]
We understand your need for offline inference and have released the code supporting this feature. You can conduct offline inference with a single line of command:
```shell
bash scripts/inference_offline.sh GPU_ID # replace GPU_ID
```
 However, due to subtle differences in the prompt processing method, the evaluation results obtained through the offline inference method may vary slightly from those provided by our original approach. We hope our update is helpful to you!
